### ISSUE TITLE
Make "WithAttachment" method PCL compatible

### ISSUE THREAD

**Issue by deckertron9000** [cjlotz/Xamarin.Plugins#19]
I was wondering if it would make sense to make the "WithAttahchment" extension method PCL compatible? (Also possibly adding a "SupportsAttachments" property to the EmailMessenger)
This would make it much easier to add attachments to emails in a truly platform independent way.

**Comment by cjlotz** [comment]
The problem with making the attachments PCL compatible is that the different platforms handle the attachments quite differently.  For Android you simply need a filepath, but for iOS you need the stream content  along with the content type and file name.  Creating an elegant API to cater for these platform differences without having platform specific code in the PCL is therefore quite difficult

**Comment by JasonHardman** [comment]
What you could do is change the WithAttachment parameters to filePath and contentType.  Android would ignore the contentType.  IOS would take the filePath to create the FileStream and to get the filename.  I'm not sure what Windows Phone needs.

**Comment by johnbeans** [comment]
I would second JasonHardman's suggestion on file attachments in iOS and Android. One common call would be much better, and I'd prefer to optimize for the case that have a path and a file type. I also don't care what Windows Phone needs.

**Comment by cjlotz** [comment]
I've just published a new beta nuget package of the plugin that adds the additional WithAttachments overload  for adding attachments from the PCL.  Check the release notes for details.  Let me know if you encounter any issues

**Comment by johnbeans** [comment]
Carel,
Works great! 
Thanks!
 John

John Beans, President
Jolly Logic
Phone: 510-914-4712
Fax: 925-553-2627


From:  Carel Lotz <notifications@github.com>
Reply-To:  "cjlotz/Xamarin.Plugins"
<reply+002dbebd3b44eb89b76162cbf1c118603249dc16ddae53d292cf000000011312b7419
2a169ce065b30d4@reply.github.com>
Date:  Tuesday, March 29, 2016 at 2:36 PM
To:  "cjlotz/Xamarin.Plugins" <Xamarin.Plugins@noreply.github.com>
Cc:  John Beans <john@jollylogic.com>
Subject:  Re: [cjlotz/Xamarin.Plugins] Make "WithAttachment" method PCL
compatible (#19)


I've just published a new beta nuget package of the plugin that adds the
additional WithAttachments overload  for adding attachments from the PCL.
Check the release notes for details.  Let me know if you encounter any
issues


You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/cjlotz/Xamarin.Plugins/issues/19#issuecomment-203118883>

**Comment by grockland** [comment]
I am testing the beta with WithAttachments from a shared Xamarin.Forms project and the compiler doesn't complain and the email is sent, but a txt/plain attachment is not included when delivered.  This using both gmail and mail programs on the emulator as well as an Android device. FYI

**Comment by cjlotz** [comment]
@grockland Does this happen for all kinds of files or only text files?  Also, is it possible to confirm that if you attach the file using the platform specific ``WithAttachment`` that it works fine?

**Comment by cjlotz** [comment]
Available in latest v.3.2.1 update
