### ISSUE TITLE
Auto dial issue

### ISSUE THREAD

**Issue by vickieallen** [cjlotz/Xamarin.Plugins#60]
I have followed the instructions on here to implement autodialling on Android. 

I have the latest version of the plugin yet when I try to add the Settings line it tells me that it doesn't exist. 

Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/5023006/24808109/90b24552-1bb2-11e7-93f1-debc52ef7360.png)

**Comment by cjlotz** [comment]
@vickieallen Are you trying to set this from within a PCL project?  Because the setting is Android specific, it is not available within a PCL project to set.  You have to set it from within an Android project.

**Comment by vickieallen** [comment]
Okay. So I'm not sure I understand where this needs to go. I have tried both as above and by creating a dependencyservice and calling into my Android project, but still get the same issue. I also tried putting it in my MainActivity.cs file. Please, can you explain where I need to put this line of code...

**Comment by cjlotz** [comment]
Vicky, can you try again after adding this in your Android project:
```
   public static class SettingsExtensions
    {
        public static Settings Settings(this IMessaging messaging)
        {
            return ((MessagingImplementation)CrossMessaging.Current).Settings;
        }
    }
```

**Comment by santanudoors** [comment]
I have the same issue I added the code in mainactivity.cs file in android project but still getting this two error:

1) 'MessagingImplementation' is inaccessible due to its protection level

2) 'IMessaging' does not contain a definition for 'Settings' and no extension method 'Settings' accepting a first argument of type 'IMessaging' could be found (are you missing a using directive or an assembly reference?)

Can you help me out please

**Comment by wallesonn** [comment]
See this.. here is the solution https://julianocustodio.com/2018/05/09/chamada-telefonica-xamarin-forms/
