### ISSUE TITLE
SMS With special Characters

### ISSUE THREAD

**Issue by caprica-dev** [cjlotz/Xamarin.Plugins#94]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.10 

Device Tested On: Samsung S6 Edge 

Simulator Tested On:

Version of VS:  VS 2017 15.6.4

Version of Xamarin:

Versions of other things you are using:

### Steps to reproduce the Behavior
Use Messaging Plugin  send a sms in Background on Android Targeting Api level 23 with special characters like "ç" in Lower Case
### Expected Behavior
Normaly send SMS
### Actual Behavior
SMS was not Send

**Comment by cjlotz** [comment]
After some testing it seems that the fix for using `SendMultipartTextMessage` requires the `android.permission.READ_PHONE_STATE` permission to be added to apps for some devices on some platforms.  Read more [here](https://stackoverflow.com/questions/43963177/why-is-smsmanager-requiring-read-phone-state-permission-on-some-devices-but-not)
